config/routes.rb
Rails.application.routes.draw do
  get '/sign_up', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :show]
  resources :photos
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  #
  # include ActsAsCommentable::Comment
  #
  # belongs_to :commentable, :polymorphic => true
  #
  # default_scope -> { order('created_at ASC') }
  #
  # # NOTE: install the acts_as_votable plugin if you
  # # want user to vote on the quality of comments.
  # #acts_as_voteable
  #
  # # NOTE: Comments belong to a user
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments
  has_many :users, through: :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :photos, through: :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
    @comments = Comment.all
    commentable = Post.create
    comment = commentable.comments.create
    comment.title = "First comment."
    comment.comment = "This is the first comment."
    comment.save
  end

  def new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "Photo Saved"
      redirect_to photos_path
    else
      render :new
    end
  end

  private

  def photo_params
    params.required(:photo).permit(:url, :caption, :category)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(current_user)
    else
      flash[:danger] = "Invalid Username or Password!"
      render :new
    end
  end

    def destroy
      session[:user_id] = nil
      redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render :new
      end
  end

  private

  def user_params
    params.required(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideabox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Logout", logout_path %>
    <% flash.each do |key, value|  %>
  <div class="flash_<%= key %>"><%= value %></div>
  <% end %>
    <%= yield %>

  </body>
</html>

app/views/photos/index.html.erb
<h1>Your Photos</h1>
<%= link_to "Add a Photo", new_photo_path %>
  <br>
  <% @photos.each do |f|  %>
    <%= image_tag f.url %>
    <br>
    <%= f.caption %>
    <br>
    <%= form_for :comment,  do |s| %>
    <p> Have a thought? </p>
      <%= s.label :text %>
      <%= s.text_field :text %>
      <%= s.submit "Add Comment" %>
      <% end %>
    <% end %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= form_for :photo, url: photos_path do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  <%= f.select :category, category: ['Funny', 'Travel', 'Tech'] %>
  <%= f.submit  %>
<% end %>

app/views/users/new.html.erb
<h1> Create an Account</h1>

<%= form_for @user do |f| %>
  <%= f.label "Username", :username %>
  <%= f.text_field :username %>
  <%= f.label "Password", :password %>
  <%= f.password_field :password %>
  <%= f.label "Confirm Password", :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %>!</h1>
<%= link_to "Photos", photos_path %>